# Generated by Django 4.2.5 on 2023-09-12 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id_classroom', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_of_week_begin', models.IntegerField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LecturerInfo',
            fields=[
                ('id_lecturer', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lecturer_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('birthday', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id_student', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('birthday', models.TextField()),
                ('PathImageFolder', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDepartmentInfo',
            fields=[
                ('id_staff', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('staff_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('birthday', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classroom')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentinfo')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='id_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lecturerinfo'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(through='main.StudentClassDetails', to='main.studentinfo'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id_attendance', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField()),
                ('attendance_status_bit', models.BooleanField()),
                ('id_classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentinfo')),
            ],
        ),
    ]
