# Generated by Django 4.2.5 on 2023-09-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='day_of_week_begin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
